<?php echo '<?php' ?>


/**
 * Autogenerated class
 * IS API project: "<?php echo $this->context->getProjectName(); ?>"
 * date/time: <?php echo date('Y-m-d H:i:s'); ?>
 
 * API URL: <?php echo $this->context->getApiUrl(); ?>
 
 */

class JsonApi extends nomvcJsonApi {

<?php foreach ($this->getActionsList() as $cmd => $title) : ?>

	/**
	 * <?php echo $cmd.' - '.$title; ?>

	 *
<?php
	$actionClass = self::toCamelCase('_'.$cmd).'Action';
	$action = new $actionClass($this->context);
 	$required_params = array();
 	$other_params = array();
	foreach($action->getParameters() as $parameter => $conf): ?>
	 * <?php echo strip_tags($parameter.' - '.$conf['description'].' ('.$conf['validator'].')');
	 	if ($conf['validator']->getOption('required')) {
	 		$required_params[] = $parameter;
	 	} else {
	 		$other_params[] = $parameter;
	 	}
	 	$params = array();
	 	if (count($required_params)) $params[] = '$'.implode(', $', $required_params);
	 	if (count($other_params)) $params[] = '$'.implode(' = null, $', $other_params).' = null';
	 ?>
	 
<?php endforeach ?>
	 *
	 */
	 public function <?php echo self::toCamelCase($cmd) ?>(<?php echo implode(', ', $params); ?>) {
<?php
	$params = array();
	foreach($required_params as $parameter) {
		$params[] = "'{$parameter}' => \${$parameter}";
	} ?>
	 	$params = array(<?php echo implode(', ', $params); ?>);<?php foreach($other_params as $parameter) : ?>

	 	<?php echo "if (\${$parameter}) \$params['{$parameter}'] = \${$parameter};"; endforeach; ?>

	 	return $this->doRequest(array('request' => array(
			'action'	=> '<?php echo $cmd ?>',
			'params'	=> $params
		)));
	 }
<?php endforeach ?>

}
